Vb 1486 update entities to ensure they are not data classess
ministryofjustice/visit-scheduler pull request #241
Opened 2022-12-09 14:59 UTC by dhirajshettymoj

## What does this pull request do?

Make entity classes non data classes and add specific equals, toString and hashCode methods for each entity. This is to get around the Intellij warning of "The data class implementations of equals(), hashCode() and toString() are not recommended for JPA entities. They can cause severe performance and memory consumption issues."

## What is the intent behind these changes?
As recommended JPA entities should not use data class implementations of equals(), hashCode() and toString(). Also converted the entities from data classes to non data classes.
_Required._

2022-12-12 10:05 UTC, AledWEvans requested changes
please read comments

2022-12-12 10:05 UTC, dhirajshettymoj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Visit.kt
> -    private set
sorry this was not intended.. seems to pass without but I will revert this back

2022-12-12 10:18 UTC, AledWEvans commented on src/main/kotlin/uk/gov/justice/digital/hmpps/visitscheduler/model/entity/Visit.kt
> -    private set
no worries

2022-12-13 11:56 UTC, dhirajshettymoj commented
Closing for now and instead raising a new merge request to main branch

2022-12-13 11:57 UTC, dhirajshettymoj commented
Closing for now and instead raising a new merge request to main branch

2022-12-13 11:57 UTC, closed without merging